"""
QR Forge - Core Logic
======================
Shared QR code generation functions.
"""

import base64
import io
import re
import uuid
from typing import Any
from urllib.parse import quote

import qrcode
from PIL import Image, ImageDraw
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _validate_email(email: str) -> bool:
    return bool(re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email))

def _validate_phone(phone: str) -> bool:
    digits = re.sub(r"[\s\-\(\)\+]", "", phone)
    return digits.isdigit() and 7 <= len(digits) <= 15

def _sanitize_url(url: str) -> str:
    url = url.strip()
    if not re.match(r"^https?://", url, re.IGNORECASE):
        url = "https://" + url
    return url

# ---------------------------------------------------------------------------
# QR image + PDF generation helpers
# ---------------------------------------------------------------------------

def _hex_to_rgba(hex_color: str) -> tuple:
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)
    return (r, g, b, 255)

def _make_qr_image(
    data: str,
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> io.BytesIO:
    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white").convert("RGBA")

    if style in ("rounded", "circle"):
        matrix = qr.modules
        box_size = 10
        border = 4
        img_size = (len(matrix) + border * 2) * box_size
        styled = Image.new("RGBA", (img_size, img_size), _hex_to_rgba(bg_color))
        draw = ImageDraw.Draw(styled)

        fg = _hex_to_rgba(fg_color)
        for row_idx, row in enumerate(matrix):
            for col_idx, module in enumerate(row):
                if module:
                    x = (col_idx + border) * box_size
                    y = (row_idx + border) * box_size
                    if style == "circle":
                        margin = 1
                        draw.ellipse(
                            [x + margin, y + margin, x + box_size - margin, y + box_size - margin],
                            fill=fg,
                        )
                    else:
                        radius = 3
                        draw.rounded_rectangle(
                            [x, y, x + box_size, y + box_size],
                            radius=radius,
                            fill=fg,
                        )
        img = styled
    else:
        pixels = img.load()
        w, h = img.size
        fg = _hex_to_rgba(fg_color)
        bg = _hex_to_rgba(bg_color)
        for x in range(w):
            for y in range(h):
                r, g, b, a = pixels[x, y]
                if (r, g, b) == (0, 0, 0):
                    pixels[x, y] = fg
                elif (r, g, b) == (255, 255, 255):
                    pixels[x, y] = bg

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf

def _make_pdf(qr_buf: io.BytesIO, title: str, subtitle: str, raw_data: str) -> str:
    pdf_buf = io.BytesIO()
    c = canvas.Canvas(pdf_buf, pagesize=letter)
    page_w, page_h = letter

    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(page_w / 2, page_h - 1.2 * inch, title)

    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawCentredString(page_w / 2, page_h - 1.6 * inch, subtitle)

    qr_size = 3.5 * inch
    qr_x = (page_w - qr_size) / 2
    qr_y = (page_h - qr_size) / 2 - 0.3 * inch
    qr_buf.seek(0)
    c.drawImage(ImageReader(qr_buf), qr_x, qr_y, qr_size, qr_size)

    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.55, 0.55, 0.55)
    
    # FIX: Strip newlines so ReportLab draws a clean, single line of text
    clean_data = raw_data.replace("\n", " ").replace("\r", "")
    display_data = clean_data if len(clean_data) <= 90 else clean_data[:87] + "..."
    c.drawCentredString(page_w / 2, qr_y - 0.35 * inch, display_data)

    c.setFont("Helvetica-Oblique", 9)
    c.setFillColorRGB(0.6, 0.6, 0.6)
    c.drawCentredString(page_w / 2, 0.6 * inch, "Generated by QR Forge")

    c.save()
    pdf_buf.seek(0)
    return base64.b64encode(pdf_buf.read()).decode("utf-8")

# ---------------------------------------------------------------------------
# Response builders
# ---------------------------------------------------------------------------

def _success(pdf_b64: str, qr_type: str, summary: str) -> dict[str, Any]:
    return {
        "success": True,
        "type": qr_type,
        "summary": summary,
        "pdf_base64": pdf_b64,
        "instructions": "Decode the pdf_base64 string and save it as a .pdf file to download your QR code.",
    }

def _error(message: str) -> dict[str, Any]:
    return {"success": False, "error": message}

# ===================================================================
# QR GENERATORS
# ===================================================================

def generate_url_qr(url: str, style: str = "square", fg_color: str = "#000000", bg_color: str = "#FFFFFF") -> dict:
    url = _sanitize_url(url)
    try:
        qr_buf = _make_qr_image(url, style, fg_color, bg_color)
        pdf_b64 = _make_pdf(qr_buf, "Website QR Code", url, url)
        return _success(pdf_b64, "url", f"QR code for {url}")
    except Exception as e:
        return _error(str(e))

def generate_wifi_qr(
    ssid: str,
    password: str,
    encryption: str = "WPA2",
    hidden: bool = False,
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    encryption = encryption.upper().strip()
    
    # FIX: Map AI's "None" output to the required "NOPASS" token
    if encryption == "NONE":
        encryption = "NOPASS"
        
    if encryption not in ("WPA", "WPA2", "WEP", "NOPASS"):
        return _error(f"Invalid encryption type: {encryption}. Use WPA, WPA2, WEP, or None.")

    enc_token = "WPA" if encryption in ("WPA", "WPA2") else encryption
    hidden_flag = "true" if hidden else "false"
    wifi_string = f"WIFI:T:{enc_token};S:{ssid};P:{password};H:{hidden_flag};;"

    try:
        qr_buf = _make_qr_image(wifi_string, style, fg_color, bg_color)
        pdf_b64 = _make_pdf(qr_buf, "WiFi QR Code", f"Network: {ssid}", wifi_string)
        return _success(pdf_b64, "wifi", f"WiFi QR for network '{ssid}'")
    except Exception as e:
        return _error(str(e))

def generate_vcard_qr(
    full_name: str,
    phone: str = "",
    email: str = "",
    organization: str = "",
    title: str = "",
    website: str = "",
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    if not full_name.strip():
        return _error("Full name is required.")
    if not phone.strip() and not email.strip():
        return _error("At least a phone number or email is required.")
    if phone and not _validate_phone(phone):
        return _error(f"Phone number looks invalid: {phone}.")
    if email and not _validate_email(email):
        return _error(f"Email looks invalid: {email}.")

    lines = ["BEGIN:VCARD", "VERSION:3.0", f"FN:{full_name.strip()}"]
    parts = full_name.strip().split()
    if len(parts) >= 2:
        lines.append(f"N:{parts[-1]};{' '.join(parts[:-1])}")
    else:
        lines.append(f"N:{full_name.strip()};")
    if phone:
        lines.append(f"TEL:{phone.strip()}")
    if email:
        lines.append(f"EMAIL:{email.strip()}")
    if organization:
        lines.append(f"ORG:{organization.strip()}")
    if title:
        lines.append(f"TITLE:{title.strip()}")
    if website:
        lines.append(f"URL:{_sanitize_url(website)}")
    lines.append("END:VCARD")
    vcard_string = "\n".join(lines)

    try:
        qr_buf = _make_qr_image(vcard_string, style, fg_color, bg_color)
        pdf_b64 = _make_pdf(qr_buf, "Contact QR Code", full_name.strip(), vcard_string)
        return _success(pdf_b64, "vcard", f"vCard QR for {full_name.strip()}")
    except Exception as e:
        return _error(str(e))

def generate_email_qr(
    email_address: str,
    subject: str = "",
    body: str = "",
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    if not _validate_email(email_address):
        return _error(f"Invalid email address: {email_address}")

    params = []
    if subject:
        params.append(f"subject={quote(subject)}")
    if body:
        params.append(f"body={quote(body)}")
    mailto = f"mailto:{email_address}"
    if params:
        mailto += "?" + "&".join(params)

    try:
        qr_buf = _make_qr_image(mailto, style, fg_color, bg_color)
        subtitle = f"To: {email_address}"
        if subject:
            subtitle += f" | Subject: {subject}"
        pdf_b64 = _make_pdf(qr_buf, "Email QR Code", subtitle, mailto)
        return _success(pdf_b64, "email", f"Email QR for {email_address}")
    except Exception as e:
        return _error(str(e))

def generate_sms_qr(
    phone_number: str,
    message: str = "",
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    if not _validate_phone(phone_number):
        return _error(f"Invalid phone number: {phone_number}.")

    sms_string = f"smsto:{phone_number.strip()}"
    if message:
        sms_string += f":{message}"

    try:
        qr_buf = _make_qr_image(sms_string, style, fg_color, bg_color)
        subtitle = f"To: {phone_number.strip()}"
        if message:
            short_msg = message if len(message) <= 50 else message[:47] + "..."
            subtitle += f" | Message: {short_msg}"
        pdf_b64 = _make_pdf(qr_buf, "SMS QR Code", subtitle, sms_string)
        return _success(pdf_b64, "sms", f"SMS QR for {phone_number.strip()}")
    except Exception as e:
        return _error(str(e))

def generate_event_qr(
    event_name: str,
    start_datetime: str,
    end_datetime: str,
    location: str = "",
    description: str = "",
    organizer_name: str = "",
    organizer_email: str = "",
    reminder_minutes: int = 15,
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    if not event_name.strip():
        return _error("Event name is required.")
    if not start_datetime.strip() or not end_datetime.strip():
        return _error("Both start and end date/time are required.")

    def _to_ical_dt(iso_str: str) -> str:
        cleaned = iso_str.strip().replace("-", "").replace(":", "")
        if "." in cleaned:
            cleaned = cleaned.split(".")[0]
        if "T" not in cleaned:
            return cleaned + "T000000"
        return cleaned

    try:
        dt_start = _to_ical_dt(start_datetime)
        dt_end = _to_ical_dt(end_datetime)
    except Exception:
        return _error("Could not parse date/time. Use ISO 8601 format like 2026-03-15T14:00:00")

    uid = str(uuid.uuid4())
    lines = [
        "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//QR Forge//EN",
        "BEGIN:VEVENT", f"UID:{uid}", f"DTSTART:{dt_start}", f"DTEND:{dt_end}",
        f"SUMMARY:{event_name.strip()}",
    ]
    if location:
        lines.append(f"LOCATION:{location.strip()}")
    if description:
        lines.append(f"DESCRIPTION:{description.strip()}")
    if organizer_email:
        cn_part = f"CN={organizer_name.strip()}" if organizer_name else f"CN={organizer_email.strip()}"
        lines.append(f"ORGANIZER;{cn_part}:mailto:{organizer_email.strip()}")
    if reminder_minutes > 0:
        lines.extend([
            "BEGIN:VALARM", "ACTION:DISPLAY",
            f"DESCRIPTION:Reminder: {event_name.strip()}",
            f"TRIGGER:-PT{reminder_minutes}M", "END:VALARM",
        ])
    lines.extend(["END:VEVENT", "END:VCALENDAR"])
    ical_string = "\r\n".join(lines)

    try:
        qr_buf = _make_qr_image(ical_string, style, fg_color, bg_color)
        subtitle = event_name.strip()
        if location:
            subtitle += f" @ {location.strip()}"
        pdf_b64 = _make_pdf(qr_buf, "Event QR Code", subtitle, ical_string)
        return _success(pdf_b64, "event", f"Calendar event QR for '{event_name.strip()}'")
    except Exception as e:
        return _error(str(e))

def generate_medical_id_qr(
    full_name: str,
    date_of_birth: str = "",
    blood_type: str = "",
    allergies: str = "",
    medications: str = "",
    medical_conditions: str = "",
    emergency_contact_name: str = "",
    emergency_contact_phone: str = "",
    emergency_contact_relation: str = "",
    organ_donor: bool = False,
    additional_notes: str = "",
    style: str = "square",
    fg_color: str = "#000000",
    bg_color: str = "#FFFFFF",
) -> dict:
    if not full_name.strip():
        return _error("Full name is required for a medical ID.")
    if emergency_contact_phone and not _validate_phone(emergency_contact_phone):
        return _error(f"Emergency contact phone looks invalid: {emergency_contact_phone}.")

    valid_blood_types = {"A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-",
                         "a+", "a-", "b+", "b-", "ab+", "ab-", "o+", "o-"}
    if blood_type and blood_type.strip() not in valid_blood_types:
        return _error(f"Unrecognized blood type: {blood_type}. Valid: A+, A-, B+, B-, AB+, AB-, O+, O-")

    sections = ["=== EMERGENCY MEDICAL ID ===", f"Name: {full_name.strip()}"]
    if date_of_birth:
        sections.append(f"DOB: {date_of_birth.strip()}")
    if blood_type:
        sections.append(f"Blood Type: {blood_type.strip().upper()}")
    if allergies:
        sections.append(f"\nALLERGIES: {allergies.strip()}")
    else:
        sections.append("\nALLERGIES: None reported")
    if medications:
        sections.append(f"MEDICATIONS: {medications.strip()}")
    if medical_conditions:
        sections.append(f"CONDITIONS: {medical_conditions.strip()}")
    if organ_donor:
        sections.append("ORGAN DONOR: Yes")
    if emergency_contact_name or emergency_contact_phone:
        sections.append("\n--- EMERGENCY CONTACT ---")
        if emergency_contact_name:
            contact_line = emergency_contact_name.strip()
            if emergency_contact_relation:
                contact_line += f" ({emergency_contact_relation.strip()})"
            sections.append(f"Contact: {contact_line}")
        if emergency_contact_phone:
            sections.append(f"Phone: {emergency_contact_phone.strip()}")
    if additional_notes:
        sections.append(f"\nNOTES: {additional_notes.strip()}")
    sections.append("\n[Generated by QR Forge]")
    medical_string = "\n".join(sections)

    try:
        qr_buf = _make_qr_image(medical_string, style, fg_color, bg_color)
        subtitle = full_name.strip()
        if blood_type:
            subtitle += f" | Blood Type: {blood_type.strip().upper()}"
        pdf_b64 = _make_pdf(qr_buf, "Emergency Medical ID", subtitle, medical_string)
        return _success(pdf_b64, "medical_id", f"Medical ID QR for {full_name.strip()}")
    except Exception as e:
        return _error(str(e))